name: Publish package to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Deploy to PYPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install build
        run: |
          python -m pip install build --user

      - name: Build the archives
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_PASSWORD }}