name: Publish package to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Deploy to PYPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/prop2po
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install build
        run: |
          python -m pip install build --user

      - name: Build the archives
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_PASSWORD }}